### ISSUE TITLE
Human

### ISSUE THREAD

**Issue by JacobWANG32** [agrignard/AAVS_Urban_Rythm_Unit_1_2024#10]
Human will be visualized as circle in this model.

They keep their schedule every day in the city and their emotion will be influenced by the amount of greenblocks.

They go to work every morning and go back home every afternoon.

The location of work and home will be visualize as geolocated polygon.

If wind is big, always shadow, to many waste_water on the road.

**Comment by HaoqiWANG-NB** [comment]
HUMAN

read shape_parliament, shape_a'beckett, chinatown;

target <- nil;

human_happiness <- 80; // default human happiness

species people skills: [moving]{  
    ...
    reflex time_to_work when: current_date.hour = start_work and objective = "resting" {
        objective <- "working" ;
	the_target <- any_location_in (working_place);
    }
		
    reflex time_to_go_home when: current_date.hour = end_work and objective = "working" {
        objective <- "resting" ;
	the_target <- any_location_in (living_place); 
    } 
    ...
}

species people skills: [moving]{
    ...
    reflex move when: the_target != nil {
	do goto target: the_target on: the_graph ; 
	if the_target = location {
	    the_target <- nil ;
	}
    }
}

ask agent (human);
	
	if human_location in shape_parliament;
		human_happiness <- human_happness - 1;
	
	elif human_location in shape_a'beckett;
		human_happiness <- human_happiness + 0.5;

	elif human_location in shape_chinatown;
		human_happiness <- human_happiness + 1;

print int (human_happiness)

**Comment by HaoqiWANG-NB** [comment]
read shape_parliament, shape_a'beckett, chinatown;

target <- nil;

human_happiness <- 80; // default human happiness

species people skills: [moving]{  
    ...
reflex time_to_work when: current_date.hour = start_work and objective = "resting" {
        
	objective <- "working" ;
	
	the_target <- any_location_in (working_place);
 }
		

reflex time_to_go_home when: current_date.hour = end_work and objective = "working" {

	objective <- "resting" ;
	
	the_target <- any_location_in (living_place); 
	
	} 
    ...

}

species people skills: [moving]{
    ...

reflex move when: the_target != nil {

	do goto target: the_target on: the_graph ; 
	
	if the_target = location {
	    
		the_target <- nil ;
		
		}
	}
}


ask agent (human);
	
	if human_location in shape_parliament;
		
		human_happiness <- human_happness - 1;
	
	elif human_location in shape_a'beckett;
		
		human_happiness <- human_happiness + 0.5;

	elif human_location in shape_chinatown;
		
		human_happiness <- human_happiness + 1;


print int (human_happiness)

**Comment by JacobWANG32** [comment]
HUMAN

read shape_parliament, shape_a'beckett, chinatown;

target <- nil;

human_happiness <- 80; // default human happiness

species people skills: [moving]{  
    ...
reflex time_to_work when: current_date.hour = start_work and objective = "resting" {
        
	objective <- "working" ;
	
	the_target <- any_location_in (working_place);
 }
		

reflex time_to_go_home when: current_date.hour = end_work and objective = "working" {

	objective <- "resting" ;
	
	the_target <- any_location_in (living_place); 
	
	} 
    ...

}

species people skills: [moving]{
    ...

reflex move when: the_target != nil {

	do goto target: the_target on: the_graph ; 
	
	if the_target = location {
	    
		the_target <- nil ;
		
		}
	}
}


ask agent (human);
	
	if human_location in shape_parliament;
		
		human_happiness <- human_happness - 1;
	
	elif human_location in shape_a'beckett;
		
		human_happiness <- human_happiness + 0.5;

	elif human_location in shape_chinatown;
		
		human_happiness <- human_happiness + 1;


print int (human_happiness)
