### ISSUE TITLE
Design Aesthetics

### ISSUE THREAD

**Issue by ArnavGoyal** [agrignard/AAVS_Urban_Rythm_Unit_1_2024#11]
I'm sharing the font style and color palette we can follow for design homogenity

Text style: [https://fonts.adobe.com/fonts/futura-pt]
Color Palette:

![p2_3](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/59308799/d587393e-936c-4aaa-8322-fa9bc7d69edf)
![U![p2_2](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/59308799/1cce436e-461b-480c-8471-2a78c7d3ba03)
![p2_1](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/59308799/4a3b3a40-78d3-4863-8e28-91e3750f76fb)

**Comment by DaoxingSun** [comment]
Logo and analysis diagram
![logo 2](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/174296906/85bfa018-374d-4422-a0dc-8432cae6ba68)
![VIENNA](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/174296906/df1b9564-6c59-4bdd-8522-bf3f2125c3a3)

**Comment by DaoxingSun** [comment]
new diagram
![daigram](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/174296906/20e2163d-cf2b-47fe-9357-c7d26894d19b)

**Comment by DaoxingSun** [comment]
[Final exhibition Folder.zip](https://github.com/user-attachments/files/16139929/Final.exhibition.Folder.zip)

**Comment by dbwng** [comment]
![colour palette](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/170797531/3b5001f3-6da1-4bb1-855e-ad961ca9b930)
![colour palette2](https://github.com/agrignard/AAVS_Urban_Rythm_Unit_1_2024/assets/170797531/21ffaac7-a915-4c94-b383-1e5301437a13)
